openapi: 3.2.0
info:
  title: IonQ Cloud Platform Jobs API
  version: v0.2
  description: '*Last updated: October 19, 2026*

    # Introduction

    Welcome to the IonQ platform! You can use our API and the `qcloud` command-line interface to submit and retrieve jobs on our quantum hardware as well as our high-performance simulator.


    Our API uses the REST architectural style; this means we provide unsurprising, resource-oriented URLs and take advantage of built-in HTTP response codes, authentication, verbs, and other features.

    We allow cross-site requests from any domain, and return JSON responses.


    If you prefer to not think about HTTP, use our OpenAPI spec to generate bindings for your language of choice. Pre-generated bindings for Python and JavaScript are coming soon.


    ## Non-breaking changes


    * Histogram example expanded to include scientific notation for a JSON numeric value.


    ## Migrating to v0.2


    ### Breaking changes


    * Calibrations endpoints has been deprecated in favor of Characterizations.


    ### New features


    * Ability to specifify target hardware generation on Job creation. e.g. `qpu.harmony` for targeting our 11-qubit system.

    * Introduces Characterizations endpoints. Enables fetching current and historic characterizations for specific targets.

    * Backends availability and other stats can now be fetched.


    ## Migrating to v0.1


    ### Breaking changes


    Prerelease version `v0.1` has one major breaking change from `v0`:


    * Canceling jobs is now done via a PUT. This allows us to more naturally support job deletion.


    ### New features


    * Completely deleting one or more jobs is now possible

    * Multiple jobs may be canceled simultaneously

    * A list of jobs may be fetched simultaneously


    ## API status


    API and quantum computer status is continuously reported at https://status.ionq.co/.

    Please subscribe for automated updates when we perform maintenance or experience an outage.


    In addition, you may use the status endpoint to check the current status of our API.


    ## Authentication'
  contact:
    name: IonQ
    email: support@ionq.co
    url: https://ionq.com/
  x-logo:
    url: https://static.ionq.co/images/ionq-logo-dark.png
    altText: IonQ Logo
    href: '#'
servers:
- url: https://api.ionq.co/v0.2
  description: Current Endpoint
- url: https://api.ionq.co/v0.1
basePath: /v0.2
security:
- API Key: []
tags:
- name: Jobs
  x-displayName: Jobs
  description: 'A **job** is the basic unit of work on the IonQ cloud.

    Whether you''re simulating a simple circuit, or submitting a program to run on our world-class hardware, you''ll send it along as a job.'
paths:
  /jobs:
    get:
      operationId: getJobs
      summary: Get Jobs
      description: '**NOTE**: If request filters are provided, this endpoint will limit responses to 1 or more specific jobs based on those filters.


        This endpoint retrieves all jobs this API key is authorized to view.'
      tags:
      - Jobs
      parameters:
      - name: id
        in: query
        schema:
          type: array
          description: If provided, will only return jobs whose UUID matches the list provided.
          items:
            type: string
            format: uuid
            description: UUID of a job
      - name: status
        in: query
        description: If provided, will only return jobs whose status matches the one provided.
        schema:
          type: string
          example: completed
          description: Status of a job.
          enum:
          - submitted
          - ready
          - running
          - canceled
          - completed
          - failed
      - name: limit
        in: query
        schema:
          type: integer
          default: 25
          minimum: 1
          maximum: 25
          description: How many objects to return.
      - name: next
        in: query
        schema:
          type: string
          format: uuid
          description: ID of next batch of resources to load.
      responses:
        '200':
          description: Successfully retrieved a list of jobs.
          content:
            application/json:
              schema:
                type: object
                description: Response body when requesting all or many jobs.
                properties:
                  jobs:
                    type: array
                    description: A list of jobs.
                    items:
                      type: object
                      description: A quantum job.
                      required:
                      - id
                      - status
                      - type
                      - request
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: aa54e783-0a9b-4f73-ad2f-63983b6aa4a8
                          description: The UUID of a job. We'll provide the UUID initially in our response to a [job creation request](#operation/createJob).
                        type:
                          type: string
                          example: circuit
                          description: The job type
                          enum:
                          - circuit
                        name:
                          type: string
                          description: A job name.
                          example: My Awesome Job
                        status:
                          type: string
                          example: completed
                          description: Status of a job.
                          enum:
                          - submitted
                          - ready
                          - running
                          - canceled
                          - completed
                          - failed
                        target:
                          type: string
                          description: Target hardware for job to run on.
                          default: simulator
                          enum:
                          - qpu.harmony
                          - qpu.aria-1
                          - simulator
                        noise:
                          description: When the target is "simulator", this field specifies optional noise parameters for simulation. (If these noise parameters are not provided, simulations will run on an ideal quantum computer model, without noise.) This field does not apply to `qpu.*` targets.
                          type: object
                          properties:
                            model:
                              type: string
                              description: Selects a noise model to apply to a simulation job. The default, `ideal`, provides perfect simulation without noise, while other noise models like `harmony` are based on noise data collected from our actual quantum computers. Note that these are simplified noise models, not intended to exactly reproduce real quantum computations.
                              enum:
                              - harmony
                              - aria-1
                              - ideal
                            seed:
                              type: integer
                              description: This is the seed value for the pseudo-random sampling and noise generation when a system noise model is specified. The seed needs to be a positive integer between 1 and 2^31. Providing a seed is optional and allows for repeatable (i.e. non-random) outcomes. If a seed is not specified, one is chosen at random and will be provided in the output for the simulation. This field does not apply to simulations using the "ideal" noise model. This field also does not apply to `qpu.*` targets.
                              example: 100
                        data:
                          description: Job execution data.
                          type: object
                          properties:
                            histogram:
                              type: object
                              description: A histogram of job event data, with probabilities possibly encoded in exponential form. While these numbers should roughly sum to 1, they may not exactly due to loss of precision.
                              example:
                                '0': 0.5
                                '1': 0.5
                                '2': 1.0e-07
                              additionalProperties: true
                        metadata:
                          type: object
                          description: User defined metadata.
                          example:
                            custom_key: a string, maximum 400 chars
                          additionalProperties: true
                        shots:
                          type: number
                          description: How many times to execute your circuit when submitting to a QPU or a "non-ideal" noisy simulator.
                          default: 100
                        gate_counts:
                          type: object
                          description: The number of gates used with this job.
                          properties:
                            1q:
                              type: number
                              example: 8
                              description: How many 1-qubit gates were used.
                            2q:
                              type: number
                              example: 2
                              description: How many 2-qubit gates were used.
                        qubits:
                          type: integer
                          example: 4
                          description: The number of qubits used with this job.
                        request:
                          type: integer
                          format: unix-timestamp
                          readOnly: true
                          example: 1490932820
                          description: The point in time this job was requested.
                        start:
                          type: integer
                          format: unix-timestamp
                          example: 1490932821
                          description: The point in time this job was started.
                        response:
                          type: integer
                          format: unix-timestamp
                          readOnly: true
                          example: 1490932834
                          description: The point in time this job was completed.
                        execution_time:
                          type: integer
                          description: The actual execution time of this job.
                          example: 13
                        predicted_execution_time:
                          type: integer
                          description: The predicted execution time of this job.
                          example: 13
                        failure:
                          type: object
                          description: Error metadata, if the job failed.
                          properties:
                            error:
                              type: string
                              description: A helpful error message.
                              example: An error occurred!
                            code:
                              type: string
                              description: A helpful error code.
                              example: internal_error
                        warning:
                          type: object
                          description: Warning metadata, if a warning is necessary.
                          readOnly: true
                          properties:
                            messages:
                              type: array
                              description: A list of warnings to emit.
                              items:
                                type: string
                  next:
                    type: string
                    format: uuid
                    description: ID of next batch of resources to load.
      x-codeSamples:
      - lang: curl
        source: "# Get all jobs:\ncurl \"https://api.ionq.co/v0.2/jobs\" \\\n  -H \"Authorization: apiKey your-api-key\"\n\n# Filter jobs by id:\ncurl \"https://api.ionq.co/v0.2/jobs?id=617a1f8b-59d4-435d-aa33-695433d7155e&id=2ccf2773-4c28-468e-a290-2f8554808a25\" \\\n  -H \"Authorization: apiKey your-api-key\"\n"
    post:
      operationId: createJob
      summary: Create a Job
      description: To submit a program to be simulated or executed on our quantum hardware, `POST` it to the `jobs` endpoint.
      tags:
      - Jobs
      requestBody:
        content:
          application/json:
            schema:
              description: Request body for creating a quantum job.
              oneOf:
              - type: object
                description: Request body for creating JSON based circuits.
                required:
                - lang
                - body
                discriminator:
                  propertyName: lang
                properties:
                  name:
                    type: string
                    description: A job name.
                    example: My Awesome Job
                  metadata:
                    type: object
                    description: User defined metadata.
                    example:
                      custom_key: a string, maximum 400 chars
                    additionalProperties: true
                  shots:
                    type: number
                    description: How many times to execute your circuit when submitting to a QPU or a "non-ideal" noisy simulator.
                    default: 100
                  target:
                    type: string
                    description: Target hardware for job to run on.
                    default: simulator
                    enum:
                    - qpu.harmony
                    - qpu.aria-1
                    - simulator
                  noise:
                    description: When the target is "simulator", this field specifies optional noise parameters for simulation. (If these noise parameters are not provided, simulations will run on an ideal quantum computer model, without noise.) This field does not apply to `qpu.*` targets.
                    type: object
                    properties:
                      model:
                        type: string
                        description: Selects a noise model to apply to a simulation job. The default, `ideal`, provides perfect simulation without noise, while other noise models like `harmony` are based on noise data collected from our actual quantum computers. Note that these are simplified noise models, not intended to exactly reproduce real quantum computations.
                        enum:
                        - harmony
                        - aria-1
                        - ideal
                      seed:
                        type: integer
                        description: This is the seed value for the pseudo-random sampling and noise generation when a system noise model is specified. The seed needs to be a positive integer between 1 and 2^31. Providing a seed is optional and allows for repeatable (i.e. non-random) outcomes. If a seed is not specified, one is chosen at random and will be provided in the output for the simulation. This field does not apply to simulations using the "ideal" noise model. This field also does not apply to `qpu.*` targets.
                        example: 100
                  lang:
                    type: string
                    description: 'The language this job is written in: json, qasm, openqasm, quipper, etc. Defaults to json.'
                    example: json
                    enum:
                    - json
                    - openqasm
                    - qasm
                    - quipper
                  body:
                    type: object
                    description: Quantum circuits for simulation or execution may be submitted as plain JSON using a [simple schema](https://static.ionq.co/schemas/circuit-v0.json).
                    required:
                    - qubits
                    - circuit
                    properties:
                      gateset:
                        type: string
                        description: Gateset to use, defaults to `qis`. Available options `qis` and `native`.
                        example: qis
                      qubits:
                        type: integer
                        description: Number of qubits your circuit requires.
                        example: 2
                      circuit:
                        type: array
                        description: Array of circuit operations.
                        example:
                        - gate: h
                          target: 0
                        - gate: cnot
                          control: 0
                          target: 1
                        - gate: gpi2
                          phase: 0.1
                          target: 1
                        - gate: ms
                          phases:
                          - 0.1
                          - 0.2
                          targets:
                          - 1
                          - 2
                        items:
                          oneOf:
                          - type: object
                            properties:
                              gate:
                                type: string
                                description: Name of gate to apply (see Supported Gates list)
                              target:
                                type: number
                                description: 'Qubit index (starting from zero) to apply gate to.

                                  **Note**: If a gate uses multiple target qubits (e.g. XX or SWAP), use the `targets` array instead.

                                  '
                              targets:
                                type: array
                                description: Use in place of `target`, if multiple gate uses multiple targets qubits.
                                items:
                                  type: number
                              control:
                                type: number
                                description: 'Qubit index (starting from zero) to use as a gate control. We support up to 7 controls per gate.

                                  **Note**: If a gate uses multiple control qubits (e.g. `CCNOT`), use the `controls` array instead.

                                  '
                              controls:
                                type: array
                                description: Use in place of `control`, if the gate uses multiple control qubits.
                                items:
                                  type: number
                              rotation:
                                type: number
                                description: Rotation angle in radians, for gates that take it, like RX
                          - type: object
                            properties:
                              gate:
                                type: string
                                description: Name of gate to apply (see Native Gates list). This controls which set of fields below can be used (phase vs phases, target vs targets).
                              target:
                                type: number
                                description: Qubit index (starting from zero) to apply gate to.
                              phase:
                                type: number
                                description: Phase of gate (measured in Turns; i.e., units of 2π)
                              phases:
                                type: array
                                description: Phases of gate (measured in Turns; i.e., units of 2π). Used for gates that target more than one ion.
                                items:
                                  type: number
                              targets:
                                type: array
                                description: Qubit index(es) (starting from zero) to apply gate to.
                                items:
                                  type: number
              - type: object
                description: Request body for creating circuits from language specific source code.
                required:
                - lang
                - body
                discriminator:
                  propertyName: lang
                properties:
                  name:
                    type: string
                    description: A job name.
                    example: My Awesome Job
                  metadata:
                    type: object
                    description: User defined metadata.
                    example:
                      custom_key: a string, maximum 400 chars
                    additionalProperties: true
                  shots:
                    type: number
                    description: How many times to execute your circuit when submitting to a QPU or a "non-ideal" noisy simulator.
                    default: 100
                  target:
                    type: string
                    description: Target hardware for job to run on.
                    default: simulator
                    enum:
                    - qpu.harmony
                    - qpu.aria-1
                    - simulator
                  lang:
                    type: string
                    description: 'The language this job is written in: json, qasm, openqasm, quipper, etc. Defaults to json.'
                    example: json
                    enum:
                    - json
                    - openqasm
                    - qasm
                    - quipper
                  body:
                    type: string
                    description: String source for a language such as qasm, openqasm, or quipper.
              discriminator:
                propertyName: lang
                mapping:
                  json: '#/components/schemas/JSONSpecificationBody'
                  openqasm: '#/components/schemas/SourceBody'
                  qasm: '#/components/schemas/SourceBody'
                  quipper: '#/components/schemas/SourceBody'
      responses:
        '200':
          description: Successfully created a Job
          content:
            application/json:
              schema:
                type: object
                description: Response body from a successful job creation.
                required:
                - id
                - status
                - request
                properties:
                  id:
                    type: string
                    format: uuid
                    example: aa54e783-0a9b-4f73-ad2f-63983b6aa4a8
                    description: The UUID of a job. We'll provide the UUID initially in our response to a [job creation request](#operation/createJob).
                  status:
                    type: string
                    description: Status of a job (always `ready`).
                    enum:
                    - ready
      x-codeSamples:
      - lang: curl
        source: "curl -X POST \"https://api.ionq.co/v0.2/jobs\" \\\n  -H \"Authorization: apiKey your-api-key\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{ \"body\": { \"qubits\": 1, \"circuit\": [ {\"gate\": \"h\", \"target\": 0} ] } }'\n"
    delete:
      operationId: deleteManyjobs
      summary: Delete Many Jobs
      description: Permanently remove many jobs from our platform. This cannot be undone.
      tags:
      - Jobs
      parameters:
      - name: ids
        in: query
        schema:
          type: array
          description: A list of job UUIDs
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully deleted requested jobs
          content:
            application/json:
              schema:
                type: object
                description: Response body from successfully deleting many jobs.
                required:
                - ids
                - status
                properties:
                  ids:
                    type: array
                    description: A list of UUIDs of deleted jobs.
                    items:
                      type: string
                      format: uuid
                      example: aa54e783-0a9b-4f73-ad2f-63983b6aa4a8
                      description: The UUID of a job. We'll provide the UUID initially in our response to a [job creation request](#operation/createJob).
                  status:
                    type: string
                    description: Status of a job (always `deleted`).
                    enum:
                    - deleted
      x-codeSamples:
      - lang: curl
        source: "curl -X DELETE \"https://api.ionq.co/v0.2/jobs\" \\\n  -H \"Authorization: apiKey your-api-key\"\n  -d '{ \\\n        \"ids\": [ \\\n            \"617a1f8b-59d4-435d-aa33-695433d7155e\", \\\n            \"2ccf2773-4c28-468e-a290-2f8554808a25\", \\\n            \"f92df2b6-d212-4f4a-b9ea-024b58c5c3e8\" \\\n        ] \\\n    }'\n"
  /jobs/{UUID}:
    get:
      operationId: getJob
      summary: Get a Specific Job
      description: This endpoint retrieves a specific job by its UUID.
      tags:
      - Jobs
      parameters:
      - name: UUID
        in: path
        required: true
        example: 617a1f8b-59d4-435d-aa33-695433d7155e
        description: The UUID of the job — this UUID is provided in the response on job creation.
        schema:
          type: string
          format: uuid
      - name: exclude
        in: query
        description: Exclude certain fields from the response (e.g., `exclude=status,device_id`).
        schema:
          type: array
          items:
            type: string
      - name: include
        in: query
        description: Only return the provided fields (e.g., `include=status,device_id`).
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: Successfully retrieved a job
          content:
            application/json:
              schema:
                type: object
                description: A quantum job.
                required:
                - id
                - status
                - type
                - request
                properties:
                  id:
                    type: string
                    format: uuid
                    example: aa54e783-0a9b-4f73-ad2f-63983b6aa4a8
                    description: The UUID of a job. We'll provide the UUID initially in our response to a [job creation request](#operation/createJob).
                  type:
                    type: string
                    example: circuit
                    description: The job type
                    enum:
                    - circuit
                  name:
                    type: string
                    description: A job name.
                    example: My Awesome Job
                  status:
                    type: string
                    example: completed
                    description: Status of a job.
                    enum:
                    - submitted
                    - ready
                    - running
                    - canceled
                    - completed
                    - failed
                  target:
                    type: string
                    description: Target hardware for job to run on.
                    default: simulator
                    enum:
                    - qpu.harmony
                    - qpu.aria-1
                    - simulator
                  noise:
                    description: When the target is "simulator", this field specifies optional noise parameters for simulation. (If these noise parameters are not provided, simulations will run on an ideal quantum computer model, without noise.) This field does not apply to `qpu.*` targets.
                    type: object
                    properties:
                      model:
                        type: string
                        description: Selects a noise model to apply to a simulation job. The default, `ideal`, provides perfect simulation without noise, while other noise models like `harmony` are based on noise data collected from our actual quantum computers. Note that these are simplified noise models, not intended to exactly reproduce real quantum computations.
                        enum:
                        - harmony
                        - aria-1
                        - ideal
                      seed:
                        type: integer
                        description: This is the seed value for the pseudo-random sampling and noise generation when a system noise model is specified. The seed needs to be a positive integer between 1 and 2^31. Providing a seed is optional and allows for repeatable (i.e. non-random) outcomes. If a seed is not specified, one is chosen at random and will be provided in the output for the simulation. This field does not apply to simulations using the "ideal" noise model. This field also does not apply to `qpu.*` targets.
                        example: 100
                  data:
                    description: Job execution data.
                    type: object
                    properties:
                      histogram:
                        type: object
                        description: A histogram of job event data, with probabilities possibly encoded in exponential form. While these numbers should roughly sum to 1, they may not exactly due to loss of precision.
                        example:
                          '0': 0.5
                          '1': 0.5
                          '2': 1.0e-07
                        additionalProperties: true
                  metadata:
                    type: object
                    description: User defined metadata.
                    example:
                      custom_key: a string, maximum 400 chars
                    additionalProperties: true
                  shots:
                    type: number
                    description: How many times to execute your circuit when submitting to a QPU or a "non-ideal" noisy simulator.
                    default: 100
                  gate_counts:
                    type: object
                    description: The number of gates used with this job.
                    properties:
                      1q:
                        type: number
                        example: 8
                        description: How many 1-qubit gates were used.
                      2q:
                        type: number
                        example: 2
                        description: How many 2-qubit gates were used.
                  qubits:
                    type: integer
                    example: 4
                    description: The number of qubits used with this job.
                  request:
                    type: integer
                    format: unix-timestamp
                    readOnly: true
                    example: 1490932820
                    description: The point in time this job was requested.
                  start:
                    type: integer
                    format: unix-timestamp
                    example: 1490932821
                    description: The point in time this job was started.
                  response:
                    type: integer
                    format: unix-timestamp
                    readOnly: true
                    example: 1490932834
                    description: The point in time this job was completed.
                  execution_time:
                    type: integer
                    description: The actual execution time of this job.
                    example: 13
                  predicted_execution_time:
                    type: integer
                    description: The predicted execution time of this job.
                    example: 13
                  failure:
                    type: object
                    description: Error metadata, if the job failed.
                    properties:
                      error:
                        type: string
                        description: A helpful error message.
                        example: An error occurred!
                      code:
                        type: string
                        description: A helpful error code.
                        example: internal_error
                  warning:
                    type: object
                    description: Warning metadata, if a warning is necessary.
                    readOnly: true
                    properties:
                      messages:
                        type: array
                        description: A list of warnings to emit.
                        items:
                          type: string
      x-codeSamples:
      - lang: curl
        source: "curl \"https://api.ionq.co/v0.2/jobs/617a1f8b-59d4-435d-aa33-695433d7155e\" \\\n  -H \"Authorization: apiKey your-api-key\"\n"
    delete:
      operationId: deleteJob
      summary: Delete a Job
      description: Permanently remove a job from our servers. This cannot be undone.
      tags:
      - Jobs
      parameters:
      - name: UUID
        in: path
        required: true
        example: 617a1f8b-59d4-435d-aa33-695433d7155e
        description: The UUID of the job — this UUID is provided in the response on job creation.
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Successfully deleted job
          content:
            application/json:
              schema:
                type: object
                description: Response body from a successful job deletion.
                required:
                - id
                - status
                properties:
                  id:
                    type: string
                    format: uuid
                    example: aa54e783-0a9b-4f73-ad2f-63983b6aa4a8
                    description: The UUID of a job. We'll provide the UUID initially in our response to a [job creation request](#operation/createJob).
                  status:
                    type: string
                    description: Status of a job (always `deleted`).
                    enum:
                    - deleted
      x-codeSamples:
      - lang: curl
        source: "curl -X DELETE \"https://api.ionq.co/v0.2/jobs/617a1f8b-59d4-435d-aa33-695433d7155e\" \\\n  -H \"Authorization: apiKey your-api-key\"\n"
  /jobs/{UUID}/status/cancel:
    put:
      operationId: cancelJob
      summary: Cancel a Job
      description: Started a job by mistake? This endpoint cancels its execution.
      tags:
      - Jobs
      parameters:
      - name: UUID
        in: path
        required: true
        example: 617a1f8b-59d4-435d-aa33-695433d7155e
        description: The UUID of the job — this UUID is provided in the response on job creation.
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Successfully cancelled job
          content:
            application/json:
              schema:
                type: object
                description: Response body from a successful job cancellation.
                required:
                - id
                - status
                properties:
                  id:
                    type: string
                    format: uuid
                    example: aa54e783-0a9b-4f73-ad2f-63983b6aa4a8
                    description: The UUID of a job. We'll provide the UUID initially in our response to a [job creation request](#operation/createJob).
                  status:
                    type: string
                    description: Status of a job (always `canceled`).
                    enum:
                    - canceled
      x-codeSamples:
      - lang: curl
        source: "curl -X PUT \"https://api.ionq.co/v0.2/jobs/617a1f8b-59d4-435d-aa33-695433d7155e/status/cancel\" \\\n  -H \"Authorization: apiKey your-api-key\"\n"
  /jobs/status/cancel:
    put:
      operationId: cancelManyJobs
      summary: Cancel Many Jobs
      description: Cancel many jobs at once.
      tags:
      - Jobs
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  description: A list of job UUIDs to cancel.
                  items:
                    type: string
                    format: uuid
                    example: aa54e783-0a9b-4f73-ad2f-63983b6aa4a8
                    description: The UUID of a job. We'll provide the UUID initially in our response to a [job creation request](#operation/createJob).
      responses:
        '200':
          description: Successfully cancelled requested jobs
          content:
            application/json:
              schema:
                type: object
                description: Response body from successfully cancelling many jobs.
                required:
                - ids
                - status
                properties:
                  ids:
                    type: array
                    description: A list of UUIDs of cancelled jobs.
                    items:
                      type: string
                      format: uuid
                      example: aa54e783-0a9b-4f73-ad2f-63983b6aa4a8
                      description: The UUID of a job. We'll provide the UUID initially in our response to a [job creation request](#operation/createJob).
                  status:
                    type: string
                    description: Status of a job (always `canceled`).
                    enum:
                    - canceled
      x-codeSamples:
      - lang: curl
        source: "curl -X PUT \"https://api.ionq.co/v0.2/jobs/status/cancel\" \\\n  -H \"Authorization: apiKey your-api-key\"\n  -d '{ \\\n        \"ids\": [ \\\n            \"617a1f8b-59d4-435d-aa33-695433d7155e\", \\\n            \"2ccf2773-4c28-468e-a290-2f8554808a25\", \\\n            \"f92df2b6-d212-4f4a-b9ea-024b58c5c3e8\" \\\n        ] \\\n    }'\n"
components:
  securitySchemes:
    API_Key:
      in: header
      name: Authorization
      type: apiKey
      description: 'We provide API keys to govern access&mdash;we''ll provision your account with one key, and more can be provided upon request.


        Every key is fully privileged within the system, and should be kept private.


        To authenticate, prefix your API Key with `apiKey ` and place it in the `Authorization` request header.

        For example: `Authorization: apiKey your-api-key`

        '
x-tagGroups:
- name: Managing Jobs
  tags:
  - jobs
- name: Building Circuits
  tags:
  - quantum_programs
- name: Characterization Data
  tags:
  - calibrations
  - characterizations
- name: Backends
  tags:
  - backends
- name: User Metadata
  tags:
  - metadata
- name: API Features
  tags:
  - api-feature-pagination
  - api-feature-response-status
- name: Telemetry
  tags:
  - status
x-provenance:
  method: harvested
  publisher: IonQ
  source: https://api.ionq.co/api-docs
  note: split by refine-openapis from the provider's own published document, verified by fetch (openapi/_original/*.fetch.json);
    stamped by stamp-openapi-provenance.py (roadmap#793)
